// Default fallback banners for when no custom banners are configured

export const defaultBanners = {
  TRENDING: [
    {
      id: 'default-trending-1',
      title: 'Trending Products',
      description: 'Discover what everyone is buying right now',
      image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1920&h=600&fit=crop',
      link: null,
      buttonText: null,
      textColor: '#ffffff',
      overlayColor: '#000000',
    },
    {
      id: 'default-trending-2',
      title: 'Hot Deals This Week',
      description: 'Shop the most popular items at great prices',
      image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1920&h=600&fit=crop',
      link: null,
      buttonText: null,
      textColor: '#ffffff',
      overlayColor: '#1a1a1a',
    },
    {
      id: 'default-trending-3',
      title: 'Customer Favorites',
      description: 'Top-rated products loved by our customers',
      image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1920&h=600&fit=crop',
      link: null,
      buttonText: null,
      textColor: '#ffffff',
      overlayColor: '#2d2d2d',
    },
  ],
  SALE: [
    {
      id: 'default-sale-1',
      title: 'Massive Sale Event',
      description: 'Save up to 50% on selected items',
      image: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'Shop Now',
      textColor: '#ffffff',
      overlayColor: '#dc2626',
    },
    {
      id: 'default-sale-2',
      title: 'Limited Time Offers',
      description: 'Incredible discounts on quality products',
      image: 'https://images.unsplash.com/photo-1607082350899-7e105aa886ae?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'View Deals',
      textColor: '#ffffff',
      overlayColor: '#ea580c',
    },
    {
      id: 'default-sale-3',
      title: 'Flash Sale',
      description: 'Hurry! Deals end soon',
      image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'Shop Sale',
      textColor: '#ffffff',
      overlayColor: '#b91c1c',
    },
  ],
  NEW_ARRIVALS: [
    {
      id: 'default-new-1',
      title: 'New Arrivals',
      description: 'Fresh products just added to our store',
      image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'Explore New',
      textColor: '#ffffff',
      overlayColor: '#0891b2',
    },
    {
      id: 'default-new-2',
      title: 'Latest Collection',
      description: 'Be the first to get our newest products',
      image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'Shop New',
      textColor: '#ffffff',
      overlayColor: '#0284c7',
    },
    {
      id: 'default-new-3',
      title: 'Just In',
      description: 'Check out what just arrived',
      image: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'View All',
      textColor: '#ffffff',
      overlayColor: '#0369a1',
    },
  ],
  FEATURED: [
    {
      id: 'default-featured-1',
      title: 'Featured Products',
      description: 'Hand-picked by our experts',
      image: 'https://images.unsplash.com/photo-1607082350899-7e105aa886ae?w=1920&h=600&fit=crop',
      link: null,
      buttonText: null,
      textColor: '#ffffff',
      overlayColor: '#7c3aed',
    },
    {
      id: 'default-featured-2',
      title: 'Editor\'s Choice',
      description: 'Premium quality products we recommend',
      image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1920&h=600&fit=crop',
      link: null,
      buttonText: null,
      textColor: '#ffffff',
      overlayColor: '#6d28d9',
    },
    {
      id: 'default-featured-3',
      title: 'Best Sellers',
      description: 'Our most popular featured items',
      image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1920&h=600&fit=crop',
      link: null,
      buttonText: null,
      textColor: '#ffffff',
      overlayColor: '#5b21b6',
    },
  ],
  CLEARANCE: [
    {
      id: 'default-clearance-1',
      title: 'Clearance Sale',
      description: 'Massive savings on clearance items',
      image: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'Shop Clearance',
      textColor: '#ffffff',
      overlayColor: '#dc2626',
    },
    {
      id: 'default-clearance-2',
      title: 'Final Markdown',
      description: 'Last chance to save big',
      image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'View Deals',
      textColor: '#ffffff',
      overlayColor: '#b91c1c',
    },
    {
      id: 'default-clearance-3',
      title: 'Limited Stock',
      description: 'Clearance items while supplies last',
      image: 'https://images.unsplash.com/photo-1607082350899-7e105aa886ae?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'Shop Now',
      textColor: '#ffffff',
      overlayColor: '#991b1b',
    },
  ],
  BRANDS: [
    {
      id: 'default-brands-1',
      title: 'Top Brands',
      description: 'Shop from the best brands in the industry',
      image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1920&h=600&fit=crop',
      link: null,
      buttonText: null,
      textColor: '#ffffff',
      overlayColor: '#1f2937',
    },
    {
      id: 'default-brands-2',
      title: 'Trusted Quality',
      description: 'Premium brands you can rely on',
      image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1920&h=600&fit=crop',
      link: null,
      buttonText: null,
      textColor: '#ffffff',
      overlayColor: '#374151',
    },
    {
      id: 'default-brands-3',
      title: 'Brand Collection',
      description: 'Explore our wide range of brands',
      image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1920&h=600&fit=crop',
      link: null,
      buttonText: null,
      textColor: '#ffffff',
      overlayColor: '#4b5563',
    },
  ],
  HOME: [
    {
      id: 'default-home-1',
      title: 'Welcome to RD Hardware',
      description: 'Your trusted source for quality products',
      image: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'Shop Now',
      textColor: '#ffffff',
      overlayColor: '#0891b2',
    },
    {
      id: 'default-home-2',
      title: 'Quality Products',
      description: 'Find everything you need in one place',
      image: 'https://images.unsplash.com/photo-1607082350899-7e105aa886ae?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'Browse Catalog',
      textColor: '#ffffff',
      overlayColor: '#0284c7',
    },
    {
      id: 'default-home-3',
      title: 'Great Deals',
      description: 'Competitive prices on all products',
      image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1920&h=600&fit=crop',
      link: null,
      buttonText: 'View Offers',
      textColor: '#ffffff',
      overlayColor: '#0369a1',
    },
  ],
};

export type BannerPlacement = keyof typeof defaultBanners;

export function getDefaultBanners(placement: BannerPlacement) {
  return defaultBanners[placement] || defaultBanners.HOME;
}
